spring.application.name=clinica
server.port=8080
server.servlet.context-path=/clinica/v1
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
